"""Core data models for the GPU Cross-Region Dynamic Scheduler."""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

import re

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# GPU instance type validation  (Security: only G5/G6/G6e allowed)
# ---------------------------------------------------------------------------

# Matches g4dn, g5, g5g, g6, g6e and any size suffix (e.g. g4dn.xlarge, g5.xlarge, g6e.2xlarge)
_GPU_INSTANCE_TYPE_PATTERN = re.compile(r"^g(4dn|5g?|6e?)\..*$")


def validate_gpu_instance_type(instance_type: str) -> str:
    """Validate that instance_type belongs to an allowed GPU family (G5/G6/G6e).

    Raises ValueError if the type is not a GPU instance.
    """
    if not _GPU_INSTANCE_TYPE_PATTERN.match(instance_type):
        raise ValueError(
            f"Instance type '{instance_type}' is not allowed. "
            f"Only GPU instance families are permitted: g4dn, g5, g5g, g6, g6e. "
            f"Example: g4dn.xlarge, g5.xlarge, g6e.2xlarge"
        )
    return instance_type


# ---------------------------------------------------------------------------
# Plan & PlanStep  (Requirement 1.2, 1.3)
# ---------------------------------------------------------------------------

class PlanStep(BaseModel):
    """A single step inside an execution plan."""

    id: str
    title: str
    tool: str = "ec2_launch_instances"
    inputs: Dict[str, Any] = Field(default_factory=dict)
    success_criteria: str = "launched == requested (FULL) or launched>0 (PARTIAL)"
    on_success: str = "done"
    on_failure: str = "next_region"
    max_attempts: int = 3
    risk_level: Literal["low", "medium", "high"] = "low"


class Plan(BaseModel):
    """Structured execution plan generated by the Controller Agent."""

    goal: str
    instance_type: str
    total_count: int
    preferred_regions: List[str]
    per_region_max: Optional[int] = None
    region_mode: Literal["multi_region", "single_region"] = "multi_region"
    steps: List[PlanStep] = Field(default_factory=list)
    stop_conditions: List[str] = Field(
        default_factory=lambda: ["remaining=0", "regions_exhausted"]
    )

    @field_validator("instance_type")
    @classmethod
    def _check_gpu_type(cls, v: str) -> str:
        return validate_gpu_instance_type(v)


# ---------------------------------------------------------------------------
# InstanceInfo & StepResult  (Requirement 4.1)
# ---------------------------------------------------------------------------

class InstanceInfo(BaseModel):
    """Details of a single launched EC2 instance."""

    instance_id: str
    instance_type: str
    az: str
    private_ip: str
    public_ip: Optional[str] = None


class StepResult(BaseModel):
    """Standardised output of each execution step."""

    status: Literal["FULL", "PARTIAL", "NONE", "ERROR"]
    requested: int
    launched: int
    remaining: int
    region: str
    instances: List[InstanceInfo] = Field(default_factory=list)
    error_code: Optional[str] = None
    message: str = ""


# ---------------------------------------------------------------------------
# NextAction  (Requirement 6.2)
# ---------------------------------------------------------------------------

class NextAction(BaseModel):
    """Decision output from the Controller Agent after each step."""

    action: Literal[
        "continue_next_region",
        "retry_same_region",
        "done",
        "abort",
    ]
    next_region: Optional[str] = None
    desired_count: Optional[int] = None
    rationale: str = ""
    final_summary: Optional[str] = None
    abort_reason: Optional[str] = None


# ---------------------------------------------------------------------------
# Region / AZ configuration models  (Requirement 8.1, 8.2)
# ---------------------------------------------------------------------------

class AZConfig(BaseModel):
    """Configuration for a single Availability Zone."""

    az_name: str
    subnets: List[str]


class RegionConfig(BaseModel):
    """Configuration for a candidate Region."""

    region: str
    priority: int = 0
    azs: List[AZConfig] = Field(default_factory=list)
    key_name: str = ""      # EC2 Key Pair name (Region-specific)
    ami_id: str = ""        # AMI ID (Region-specific)


class FallbackGroup(BaseModel):
    """Geographic compliance fallback group.

    Defines which consumer_regions map to which fallback_regions.
    A consumer_region can only launch instances within its group's
    fallback_regions. Requests from regions not in any group are rejected.
    """

    consumer_regions: List[str]
    fallback_regions: List[str]




# ---------------------------------------------------------------------------
# FilterSet, InstanceSummary, TerminatedInstance, DeleteResult
# (Requirement 3.1, 3.2, 3.3)
# ---------------------------------------------------------------------------

class FilterSet(BaseModel):
    """查询和删除操作的过滤条件集合。"""

    region: Optional[str] = None
    instance_type: Optional[str] = None
    subnet_id: Optional[str] = None
    instance_ids: Optional[List[str]] = None
    private_ips: Optional[List[str]] = None
    state: str = "running"
    tags: Optional[Dict[str, str]] = None

    def is_empty(self) -> bool:
        """检查是否所有过滤字段均为空（state 默认值不算）。"""
        return (
            self.region is None
            and self.instance_type is None
            and self.subnet_id is None
            and not self.instance_ids
            and not self.private_ips
            and not self.tags
        )


class InstanceSummary(BaseModel):
    """查询结果中每个实例的摘要信息。"""

    instance_id: str
    instance_type: str
    private_ip: str
    public_ip: Optional[str] = None
    subnet_id: str
    az: str
    state: str
    launch_time: str


class TerminatedInstance(BaseModel):
    """单个被终止实例的状态信息。"""

    instance_id: str
    current_state: str


class DeleteResult(BaseModel):
    """删除操作的返回结果。"""

    deleted_count: int
    terminated_instances: List[TerminatedInstance] = Field(default_factory=list)
    errors: List[str] = Field(default_factory=list)

